# -*- coding: utf-8 -*-
"""Assignment8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9e0cLDb_CMMP3GQgHFEIpXZmStABmlk
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

dataset = sns.load_dataset('titanic')
dataset.head()

sns.histplot(dataset['fare'], kde=True, linewidth=0);

sns.jointplot(x='age', y='fare', data=dataset);