# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opUXOyXdzOURWTTXb96RAJymCxFThk_F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

df = pd.read_csv("Iris.csv")
df.head()

'Iris-setosa'
setosa = df['Species'] == 'Iris-setosa'
df[setosa].describe()
'Iris-versicolor'
versicolor = df['Species'] == 'Iris-versicolor'
df[versicolor].describe()
'Iris-virginica'
virginica = df['Species'] == 'Iris-virginica'
df[virginica].describe()

df.dtypes
df.dtypes.value_counts()