# -*- coding: utf-8 -*-
"""Assignment10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15kA47ig9PZlF7YDzWAGbcfsGxvkhX5-O
"""

import seaborn as sns
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
dataset = sns.load_dataset('iris')
# df = pd.read_csv(r"C:\Users\bhakt\OneDrive\Desktop\DSBDA\Iris.csv")
# print(df)
dataset.head()

import matplotlib.pyplot as plt
fig, axes =plt.subplots(2,2,figsize  =(16,9))
sns.boxplot( y='petal_length',x='species',data=dataset, ax=axes[0,0])
sns.boxplot( y='petal_width',x='species',data=dataset, ax=axes[0,1])
sns.boxplot( y='sepal_length',x='species',data=dataset, ax=axes[1,0])
sns.boxplot( y='sepal_width',x='species',data=dataset, ax=axes[1,1])

import matplotlib.pyplot as plt
fig, axes =plt.subplots(2,2,figsize  =(16,9))
sns.histplot(dataset['sepal_length'], ax=axes[0,0])
sns.histplot(dataset['sepal_width'], ax=axes[0,1])
sns.histplot(dataset['petal_length'], ax=axes[1,0])
sns.histplot(dataset['petal_width'], ax=axes[1,1])