# -*- coding: utf-8 -*-
"""Assignment9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWYyW1ChMvn8pQTnYQ9urAjeISLql6uj
"""

import seaborn as sns
dataset=sns.load_dataset("titanic")
dataset.head()

sns.boxplot(x='sex', y='age', data=dataset)

sns.boxplot(x='sex', y='age', data=dataset, hue='survived')