# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkC0dT4MervIfUSSTxRAEmht9skhCXyx
"""

import pandas as pd
import numpy as np

df=pd.read_csv("StudentsPerformanceTest1.csv")

df

#Checking for missing values using isnull()

df.isnull()

series = pd.isnull(df["math score"])
df[series]

#Checking for missing values using notnull()

df.notnull()

series1 = pd.notnull(df["math score"])
df[series1]

#Filling missing values using dropna(), fillna(), replace()

#For replacing null values with NaN

missing_values = ["Na", "na"]
df = pd.read_csv("StudentsPerformanceTest1.csv", na_values =
missing_values)
df

#Filling null values with a single value

#filling missing value using fillna()

ndf=df
ndf.fillna(0)

#Filling null values in dataset
#To fill null values in dataset use inplace=true

m_v=df['math score'].mean()
df['math score'].fillna(value=m_v, inplace=True)
df

#Filling a null values using replace() method

ndf.replace(to_replace = np.nan, value = -99)

#To Drop rows if all values in that row are missing

ndf.dropna(how = 'all')

#To Drop columns with at least 1 null value.

ndf.dropna(axis = 1)

#To drop rows with at least 1 null value in CSV file.
#making new data frame with dropped NA values

new_data = ndf.dropna(axis = 0, how ='any')
new_data