# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETHxv5UJpKIdlnyAUK0G6i5exQVq5hBq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x=np.array([95,85,80,70,60])
y=np.array([85,95,70,65,70])

model= np.polyfit(x, y, 1)

model

predict = np.poly1d(model)
predict(65)

y_pred= predict(x)
y_pred

from sklearn.metrics import r2_score
r2_score(y, y_pred)

y_line = model[1] + model[0]* x
plt.plot(x, y_line, c = 'r')
plt.scatter(x, y_pred)
plt.scatter(x,y,c='r')